### ISSUE TITLE
Feature Request: Make snippets accessible with files with .es extensions.

### ISSUE THREAD

**Issue by skirankumar7** [deerawan/vscode-elasticsearch-snippets#2]
_We have another extension that enables us to write queries like kibana but there we are not able to get snippets. that vs extension uses **.es** as the file extension._

Pls have a look at this extension once.

[https://marketplace.visualstudio.com/items?itemName=ria.elastic](https://marketplace.visualstudio.com/items?itemName=ria.elastic)
[](url)

**Please make it accessible with all file extensions if possible.**

Thanks........

**Comment by deerawan** [comment]
Thank you for your submitted issue @skirankumar7. Will take a look at it.

**Comment by deerawan** [comment]
@skirankumar7 just published version 1.1.0 that support `.es` extension

**Comment by skirankumar7** [comment]
Great Thanks 💯
